---
abstract: 'Imports a Log4Perl handle with category'
author:
  - 'Andreas Hernitscheck <ahernit@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log4Perl-ImportHandle
requires:
  Exporter::AutoClean: '0'
  Log::Log4perl: '0'
version: '0.031'
